name: Documentation Issue
description: Report missing, unclear, or incorrect documentation
title: "[Docs]: "
labels: ["documentation"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Help us improve our documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs improvement?
      options:
        - API Documentation
        - User Guide
        - Developer Guide
        - Setup/Installation
        - Architecture Docs
        - Component Docs
        - README
        - Contributing Guidelines
        - Code Comments
        - Other
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: Issue Description
      description: What's wrong with the current documentation?
      placeholder: |
        - Missing information
        - Incorrect information
        - Unclear explanation
        - Outdated content
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Documentation Location
      description: Where is this documentation located?
      placeholder: |
        File path, URL, or section reference
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How should we improve this documentation?
      placeholder: Describe what you'd like to see

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might be helpful

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to help fix this?
      options:
        - label: I'd like to submit a PR to fix this documentation
